CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE book_collection (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    collection_name TEXT NOT NULL
);

CREATE TABLE book (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    collection_id INTEGER
        REFERENCES book_collection(id) ON DELETE CASCADE NOT NULL,
    finished TEXT NOT NULL,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    genre TEXT NOT NULL,
    isbn_id TEXT NOT NULL,
    year_published TEXT NOT NULL,
    description TEXT NOT NULL,
    bookmark_page TEXT NOT NULL
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_id INTEGER
        REFERENCES book(id) ON DELETE CASCADE NOT NULL,
    book_comment TEXT NOT NULL,
    book_rating TEXT NOT NULL
);